name: bit off
url: http://www.bitoff.cz
author: Jan Vlnas
author_uri: http://jan.vlnas.cz/
tag_uri: "tag:bitoff.cz,2014-03-10:"
safe: true
exclude: [Gemfile, Gemfile.lock, Guardfile, README.md]
timezone: Europe/Prague

permalink: :title/
paginate_path: 'page:num'

markdown:    kramdown
kramdown:
  auto_ids: true
  entity_output: as_input
  toc_levels: 1..2
  smart_quotes: sbquo,lsquo,bdquo,ldquo
  header_offset: 1
  parse_block_html: true
  # transliterated_header_ids: true
gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      license: CC0-1.0
      license_url: http://creativecommons.org/publicdomain/zero/1.0/
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
