name: bit off
url: http://bitoff.cz

safe: true
exclude: [Gemfile, Gemfile.lock, Guardfile, README.md]
timezone: Europe/Prague

permalink: :title/
paginate_path: 'page:num'

pygments:    true
markdown:    kramdown
kramdown:
  auto_ids: true
  entity_output: as_input
  toc_levels: 1..2
  smart_quotes: sbquo,lsquo,bdquo,ldquo
  header_offset: 1
  parse_block_html: true
  # transliterated_header_ids: true
